materials:
  - minecraft:wooden
  - minecraft:stone
  - minecraft:iron
  - minecraft:golden
  - minecraft:diamond
  - minecraft:netherite
# overwrites:
#   minecraft:diamond_pickaxe: minecraft:cactus
